### ISSUE TITLE
[Question] metadataServiceUri with multiple zk servers

### ISSUE THREAD

**Issue by hiscal2015** [apache/bookkeeper#1756] opened 2018-10-24 07:06 UTC
Hi, 

From the documents, I can see zkServers parameter has been deprecated in favor of using metadataServiceUri, but I can't see any example to define metadataServiceUri with multiple zk servers? Please help, thanks.
```
zk+hierarchical://localhost:2181/ledgers
```
Is it something like this?
```
zk+hierarchical://server1:2181/ledgers,zk+hierarchical://server2:2181/ledgers,zk+hierarchical://server3:2181/ledgers
```

**Comment by eolivelli** [comment] 2018-10-24 16:09
No, it should be like
zk://server2:port,server2:port/ledgers

**Comment by eolivelli** [comment] 2018-10-28 21:08
@hiscal2015 can you try with my suggested URI?

**Comment by hiscal2015** [comment] 2018-10-29 02:19
@eolivelli Sorry for delay, looks format zk://server1:port,server2:port,server3:port/ledgers does not work,

I tried with zk+hierarchical://server1:2181/ledgers,zk+hierarchical://server2:2181/ledgers,zk+hierarchical://server3:2181/ledgers, it works fine, can you have a double check? Thanks a lot.

**Comment by eolivelli** [comment] 2018-10-29 07:00
This sounds to me as a big problem.
I have to performs trials and reproduce your case.
Are you using that config both on bookie and client?

**Comment by hiscal2015** [comment] 2018-10-29 07:04
Looks like the setting is only available on bookie, client only needs webservice and broker url.

**Comment by sijie** [comment] 2018-10-29 18:46
@eolivelli I think the question how current code extracts zk servers from metadata service uri. I know dlog uri handles ';' and converts it to ','. but I am not very sure about the new metadata service uri, have to look more into this.

**Comment by sijie** [comment] 2018-10-30 18:55
@hiscal2015 any luck with `zk://server1:port;server2:port;server3:port/ledgers`?

**Comment by hiscal2015** [comment] 2018-11-01 02:36
@sijie My cluster was destroyed days ago, I'll get it back to you once cluster coming back again.

**Comment by sijie** [comment] 2018-11-01 05:59
@hiscal2015 cool thank you

**Comment by sijie** [comment] 2018-11-10 01:15
@hiscal2015 I am closing this issue since the question is answered. If you still see the issue, please reopen it.

**Closed by sijie** 2018-11-10 01:15 UTC
Labels: area/metadata, type/question

**Comment by hiscal2015** [comment] 2018-11-28 07:13
@sijie @eolivelli 

Today I changed metadataServiceUri to zk://server1:port;server2:port;server3:port/ledgers below logs:

```
Nov 28 15:08:46 bookkeeper[1105]: 2018-11-28 15:08:46,217 - INFO  - [main:ZKMetadataDriverBase@186] - Initialize zookeeper metadata driver at metadata service uri zk+hierarchical://10.10.100.17:2181;10.10.100.31:2181;10.10.100.27:2181/ledgers : zkServers = 10.10.100.17:2181,10.10.100.31:2181,10.10.100.27:2181, ledgersRootPath = /ledgers.
```

Is that means this is succeed?

**Comment by riverman282915** [comment] 2020-03-03 14:35
Hi I can't get this to work.. 
I tried with different values, yet all i get is 
`14:13:07.675 [main] INFO  org.apache.bookkeeper.meta.zk.ZKMetadataDriverBase - Initialize zookeeper metadata driver at metadata service uri zk+null://localhost:2181/ledgers : zkServers = lo
Caused by: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
calhost:2181, ledgersRootPath = /ledgers.
`

here is how my bookie.conf looks like. can you please help me figure out the format..
`
#############################################################################
## ZooKeeper parameters
#############################################################################

# A list of one of more servers on which Zookeeper is running.
# The server list can be comma separated values, for example:
#zkServers=zk-0:2181,zk-1:2181,zk-2:2181
#zkServers=10.42.3.12:2181,10.42.4.8:2181,10.42.5.6:2181
#zkServers=localhost:2181
#metadataServiceUri=zk+hierarchical://zk-0:2181/ledgers,zk+hierarchical://zk-1:2181/ledgers,zk+hierarchical://zk-2:2181/ledgers
metadataServiceUri=zk+hierarchical://10.42.3.12:2181/ledgers,zk+hierarchical://10.42.4.8:2181/ledgers,zk+hierarchical://10.42.5.6:2181/ledgers
`
