### ISSUE TITLE
Bookie send a lot of request to zookeeper when cluster is degraded

### ISSUE THREAD

**Issue by truong-hua** [apache/bookkeeper#3529] opened 2022-10-13 17:16 UTC
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do?
I'm using Bookeeper 4.14.4 and runing a 5 nodes cluster. When one node of my bookie cluster is down, the bookie cluster send a lot of request to zookeeper and causes ZK CPU usage always over 100%.
The issue gone when the failed node is recover and rejoin in to the cluster properly.

This is my JAVA env:
```
openjdk 11.0.13 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+8-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.13+8-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
```

The zookeeper version: 3.7.1

- What did you expect to see?
Bookie should not causes ZK CPU consumption when the cluster is degraded.

- What did you see instead?
ZK CPU stuck at >100% and it causes more server performance problems.

**Comment by dlg99** [comment] 2022-10-17 04:19
The problem is most likely related to Autorecover and Auditor.
I'd start by looking at AR and auditor configuration to check if anything differs from the default, try to disable AR on bookies, and run it as a separate process, starting with one AR node. There also logs and metrics that should help you understand if the AR of Auditor is the one generating load.

**Comment by shoothzj** [comment] 2024-05-05 07:11
Closed by no updates. Feel free to reopen it if you have more informations or way to reproduce.  

Also you can try the master code, recently we merged some pr while reduce the zookeeper pressure during gc

**Closed by shoothzj** 2024-05-05 07:11 UTC
