### ISSUE TITLE
Serious Performance problem caused by #3239

### ISSUE THREAD

**Issue by gaozhangmin** [apache/bookkeeper#3759] opened 2023-02-01 02:16 UTC
**BUG REPORT**

***Describe the bug***
#3239 addressed the replication problem of empty ledger, which means the first entry id is `INVALID_ENTRY_ID`.  

The replicationWorker will replicate these empty ledgers, LINE 441 opened these empty ledgers with `openLedgerNoRecovery`. In method `openLedgerNoRecovery`, ` readLastConfirmed` request will be send to server if the fragment is opened. 
https://github.com/apache/bookkeeper/blob/c7cc668230b7a2d5f114f37709d01a1449caea12/bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/ReplicationWorker.java#L432-L481

Let us check how the server processes the readLastConfirmed request. LINE 547 tries to getLastEntry if the request entry id is `LAST_ADD_CONFIRMED `
https://github.com/apache/bookkeeper/blob/c7cc668230b7a2d5f114f37709d01a1449caea12/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java#L542-L549

Finally, it goes to here. Try to get the last entry id from RocksDB, For a non-existed entry, it searched the a range of ledgers from current ledger id to `Long.MAX_VALUE`.  This search will run for 5mins in my prod env. This caused the slowly process of  read request and filled up the read request queue finally.

![image](https://user-images.githubusercontent.com/9278488/215928243-e511f5e6-5a18-4167-91f5-4c00d3959cb3.png)

https://github.com/apache/bookkeeper/blob/c7cc668230b7a2d5f114f37709d01a1449caea12/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/EntryLocationIndex.java#L116-L138

**Comment by hangc0276** [comment] 2023-02-02 09:51
Hi @gaozhangmin , thanks for raising this issue.
https://github.com/apache/bookkeeper/pull/3239 mark the `OPEN` state `Empty` ledgers, whose ensemble has dead bookies, as under-replicated in Auditor's checkAllLedgers stage. IMO, it makes sense, otherwise, those ledgers can't be replicated and block the decommissioning process.

When those `OPEN` state `Empty` ledgers are fenced, the bookie client will trigger a fence readLAC, which will fall into the  `locationsDb.getFloor(maxEntryId.array)` call, and the key does not exist in the RocksDB due to the ledger is empty.

From the performance picture you provided, the `locationsDb.getFloor(maxEntryId.array)` costs 316s, which is unacceptable. The root cause may be related to the RocksDB, not the `OPEN` state `Empty` ledgers marked as under-replicated behavior.

I have a few questions about this issue.
  - Would you please the size of your RocksDB, including storage size and the number of keys?
  - For those `OPEN` state and not `Empty` ledgers, if you call getLAC, it will also fall into the `locationsDb.getFloor(maxEntryId.array)`, does it also cost so much time?
  - Would you write a test to open your RocksDB, and call `locationsDb.getFloor(maxEntryId.array)` for an existed and non-existed legerId, to see the time cost?

**Comment by dlg99** [comment] 2023-02-07 20:14
@gaozhangmin Thank you, this looks like an interesting problem. 

+1 to the @hangc0276 's questions

> For a non-existed entry, it searched the a range of ledgers from current ledger id to Long.MAX_VALUE

I think there is a misunderstanding.

```java
    private long getLastEntryInLedgerInternal(long ledgerId) throws IOException {
        LongPairWrapper maxEntryId = LongPairWrapper.get(ledgerId, Long.MAX_VALUE);

        // Search the last entry in storage
        Entry<byte[], byte[]> entry = locationsDb.getFloor(maxEntryId.array);
```

`LongPairWrapper.get(ledgerId, Long.MAX_VALUE)` is a key that consists of (ledgerId, entryId) and not a (ledgerId, the last ledger id).

`locationsDb.getFloor` will use it as a max boundary to find a max key smaller or equal to this, if that matches the same ledgerId => we have last entryId, otherwise no entry found. 
This is implemented in KeyValueStorageRocksDB:
```
    public Entry<byte[], byte[]> getFloor(byte[] key) throws IOException {
        try (Slice upperBound = new Slice(key);
                 ReadOptions option = new ReadOptions(optionCache).setIterateUpperBound(upperBound);
                 RocksIterator iterator = db.newIterator(option)) {
            iterator.seekToLast();
            if (iterator.isValid()) {
                return new EntryWrapper(iterator.key(), iterator.value());
            }
        }
        return null;
    }
```

Now the real question is what's going on with `seekToLast`.
I think the problem is similar to https://github.com/facebook/rocksdb/issues/261
```
this post on our discussion group might be insightful: https://www.facebook.com/groups/rocksdb.dev/permalink/604723469626171/. 
Since deletes are not actually deletes, but rather tombstones (which get cleaned up after a compaction), 
your iterator might have to skip a bunch of deletes the get to the first key in the database.
```

This leads us to https://github.com/apache/bookkeeper/pull/2686 (reverted in https://github.com/apache/bookkeeper/pull/3144) 
There should be a way to check number of tombstones or get metrics from RocksDb (sorry, I never dealt with this).
there should be a way to trigger compaction on RocksDB. or maybe the search in your case got slowed down by running compaction.

**Closed** 2023-03-22 07:04 UTC
Labels: type/bug

**Comment by TakaHiR07** [comment] 2024-11-15 03:51
I also encounter this issue in bookie-4.16.4, how does this issue be fixed ? @gaozhangmin
