### ISSUE TITLE
Bookeeper disk space is not freed

### ISSUE THREAD

**Issue by czhfe** [apache/bookkeeper#3079] opened 2022-03-03 04:49 UTC
**BUG REPORT**

***Describe the bug***

Bookkeeper disk space is not freed, through troubleshooting found that the file handle is not freed.

***Expected behavior***

Release file handles normally to free up disk space.

***Screenshots***
![image](https://user-images.githubusercontent.com/19341806/156498122-8cbd08e7-e8d2-4d29-829d-4bf6148ecaa1.png)

**Comment by shoothzj** [comment] 2024-03-29 07:36
Closing this issue since no way to reproduce it. Feel free to reopen it if you find way to reproduce.

**Closed by shoothzj** 2024-03-29 07:36 UTC
Labels: type/bug
