### ISSUE TITLE
Autorecovery may hang indefinitely when zookeeper connection blips

### ISSUE THREAD

**Issue by karanmehta93** [apache/bookkeeper#2302] opened 2020-04-04 01:39 UTC
**BUG REPORT**

***Describe the bug***

In our clusters, @reddycharan and @jvrao caught this issue. In certain circumstances, all AR processes were running but not performing any replication. Thus ledgers remain under-replicated for periods more than the threshold defined by our monitoring system. The reason is that the latch [here](https://github.com/apache/bookkeeper/blob/master/bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/ZkLedgerUnderreplicationManager.java#L606) gets countdown only under certain conditions, listed [here](https://github.com/apache/bookkeeper/blob/master/bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/ZkLedgerUnderreplicationManager.java#L587-L598). 

***To Reproduce***

Imagine that a cluster is in steady state. Since there is no ledger to replicate, AR process is waiting around for a zk watcher. Due to a n/w partition, the client gets partitioned, AR process gets a `ConnectionLoss` event and the latch stops waiting. The retry mechanism kicks in, sets a local watch [here](https://github.com/apache/bookkeeper/blob/master/bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/ZkLedgerUnderreplicationManager.java#L599). When the zk comes back up, the first event we would receive is `SyncConnected`. We would process the watcher in that case without ever reducing the countdownlatch value. This causes AR process to get stuck forever. 

Note that, this is just a single scenario. This can happen in cases when AuthFailures are recovered or other zk events that might get added in future.

Coming up with a test case is hard since we need to get the exact race condition in there. However I did verify it with the help of breakpoints in the IDE and can confirm.

***Expected behavior***

AR should start processing on any event it receives from zookeeper

***Fix***

Decrement the countdown latch irrespective of the event received.

@eolivelli @sijie This can cause serious impact. Workaround is restarting all the hung processes, which can be operationally challenging.

**Comment by sijie** [comment] 2020-04-09 22:26
@karanmehta93 It seems that you have found the root cause. Are you going to contribute a bug fix?

**Comment by karannparikh** [comment] 2020-04-10 15:45
Hey Sijie, I will be contributing the bug fix.

**Comment by karanmehta93** [comment] 2020-04-10 19:19
Just as a heads up, we don't have a integration test for it, but the fix is verified manually.
We need some plumbing to our test infra to accomplish it, which might take a while.

**Comment by Ghatage** [comment] 2020-04-14 18:32
@karanmehta93 I think you tagged the wrong karan parikh.

**Comment by Ghatage** [comment] 2020-10-05 22:46
@karannparikh any update? Looking forward to your first contribution to BK!

cc @eolivelli @sijie

**Comment by karannparikh** [comment] 2020-10-23 01:22
Hey @Ghatage, I will be submitting my fix for review by next week or over the weekend. Looking forward to my first contribution.

**Comment by shoothzj** [comment] 2024-05-07 00:32
closed by #2471

**Closed by shoothzj** 2024-05-07 00:32 UTC
Labels: type/bug, triage/week-15
