### ISSUE TITLE
Make an official bookkeeper docker image

### ISSUE THREAD

**Issue by zhaijack** [apache/bookkeeper#498] opened 2017-09-06 03:36 UTC
As discussed in the email, seems we need to make an official docker image, similar to [zookeeper’s](https://hub.docker.com/_/zookeeper/) or Flink's way.  

Here are some info:
[1] https://docs.docker.com/docker-hub/official_repos/
[2] https://github.com/docker-library/docs
[3] https://flink.apache.org/news/2017/05/16/official-docker-image.html

To achieve it, we may need to go through the official process, and open a dedicated repo for bookkeeper docker.

**Comment by zhaijack** [comment] 2017-09-06 13:24
@caiok will handle this issue after discussion.

**Comment by eolivelli** [comment] 2017-09-06 13:26
@sijie is there any way to assign this issue to @caiok ? 
on JIRA we had the ability to assign issue to contributors

**Comment by zhaijack** [comment] 2017-09-06 13:31
@sijie , I recall you assigned issues to @caiok before. But seems I could not do it, Would you please help assign it again?

**Comment by sijie** [comment] 2017-09-07 00:43
I think if @caiok make a comment here, we might be able to assign the issue to him. Otherwise, we don't have any way to assign issue to contributors outside of ASF organization.

**Comment by caiok** [comment] 2017-09-07 12:14
@sijie @zhaijack Ok, let's see if the issue is now assignable to me

**Comment by eolivelli** [comment] 2017-09-07 12:17
I still cannot assign  the issue to @caiok, maybe @sijie will be able

**Comment by jiazhai** [comment] 2017-09-07 15:08
seem to me, not able to assign.

**Comment by sijie** [comment] 2017-09-07 16:31
hmm I can't assign either.

**Comment by ivankelly** [comment] 2018-03-19 10:33
Closing this issue. We have an image now, and improvements are being tracked in #335

**Closed by ivankelly** 2018-03-19 10:33 UTC
Labels: area/docker, type/task
